config/routes.rb
Rails.application.routes.draw do

  resources :requests, only: [:index, :edit, :show, :destroy, :update, :put]

  resources :animals do
    resources :requests, only: [:new, :create]
  end
  get 'sessions/new'
  resources :events

  root             'static_pages#home'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

end

app/views/layouts/application.html.erb
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!DOCTYPE html>
<html>
<head>
  <title>AdoptionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <nav>
    <div class="nav-wrapper">
      <a href="#" class="Logo">Adopt Life</a>

      <ul id="nav-mobile" class="right hide-on-med-and-down">

        <li><a href="sass.html"><i class="large material-icons">search</i></a></li>
       <li><%= link_to "Inicio", root_path %></li>
        <li><%= link_to "Eventos", events_path %></li>
        <li><%= link_to "Perfil", current_user %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %> </li>


      </ul>
    </div>
  </nav>

</head>
<body>


<%#= porque vergas tienes dos "yields"? BORRE UN PEDO, NO DEBRIA ESTAS  link_to 'Add user', new_user_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<%= yield %>
 <%# debug(params) if Rails.env.development? %>

</body>
</html>